#pragma once

#include "shirley/arch.hpp"

namespace shirley::arch::x86_64 {

// GDT 中的段選擇子。順序依 SYSRET 的要求排列：
// null / kernel code / kernel data / user data / user code / TSS。
//
// The GDT selectors. The order is the one SYSRET requires:
// null / kernel code / kernel data / user data / user code / TSS.
constexpr std::uint16_t kernel_code_selector = 0x08;
constexpr std::uint16_t kernel_data_selector = 0x10;
constexpr std::uint16_t user_data_selector = 0x18 | 3;
constexpr std::uint16_t user_code_selector = 0x20 | 3;
constexpr std::uint16_t tss_selector = 0x28;

// 中斷發生時由 interrupt.S 依此順序建立的暫存器影像。
// 欄位順序必須與 interrupt.S 的 push 順序完全一致。
//
// The register image interrupt.S builds on the stack. The field order must
// match the push order in interrupt.S exactly.
struct InterruptFrame {
    std::uint64_t r15, r14, r13, r12, r11, r10, r9, r8;
    std::uint64_t rbp, rdi, rsi, rdx, rcx, rbx, rax;
    std::uint64_t vector, error_code;
    std::uint64_t rip, cs, rflags, rsp, ss;
};

// CPU 辨識與基本功能啟用。
// CPU identification and basic feature enablement.
void cpu_initialize();
const char* cpu_vendor_string();
// 分頁表需要知道是否可以使用 NX 位元。
// The page tables need to know whether the NX bit is available.
bool cpu_nx_supported();
bool cpu_sse_enabled();

// GDT 與 TSS。
// The GDT and the TSS.
void gdt_initialize();
void gdt_set_kernel_stack(std::uint64_t stack_top);

// IDT 與中斷處理常式表。
// The IDT and the interrupt handler table.
void idt_initialize();
bool idt_register(unsigned vector, InterruptHandler handler, void* context);
void idt_unregister(unsigned vector);

} // namespace shirley::arch::x86_64

extern "C" {
// 由 segment.S 提供的特權指令包裝。
// Privileged instruction wrappers provided by segment.S.
void x86_64_load_gdt(const void* pointer, std::uint16_t code_selector, std::uint16_t data_selector);
void x86_64_load_idt(const void* pointer);
void x86_64_load_tss(std::uint16_t selector);
[[noreturn]] void x86_64_enter_userspace(std::uint64_t entry, std::uint64_t stack,
                                         std::uint16_t code_selector, std::uint16_t data_selector);
// 由 interrupt.S 產生的 256 個中斷入口；每個入口佔用相同的位元組數，
// 實際間距由頭尾兩個符號反推，不必在組語與 C++ 兩邊各寫一次。
//
// The 256 interrupt entry points generated by interrupt.S. Each occupies the
// same number of bytes; the stride is derived from these two symbols rather
// than written down in both the assembly and the C++.
extern const char x86_64_isr_stubs[];
extern const char x86_64_isr_stubs_end[];
}
