#pragma once

#include "shirley/arch.hpp"

namespace shirley::arch::x86_64 {

// GDT 中的段選擇子。順序依 SYSRET 的要求排列：
// null / kernel code / kernel data / user data / user code / TSS。
//
// The GDT selectors. The order is the one SYSRET requires:
// null / kernel code / kernel data / user data / user code / TSS.
constexpr std::uint16_t kernel_code_selector = 0x08;
constexpr std::uint16_t kernel_data_selector = 0x10;
constexpr std::uint16_t user_data_selector = 0x18 | 3;
constexpr std::uint16_t user_code_selector = 0x20 | 3;
constexpr std::uint16_t tss_selector = 0x28;

// 中斷發生時由 interrupt.S 依此順序建立的暫存器影像。
// 欄位順序必須與 interrupt.S 的 push 順序完全一致。
//
// The register image interrupt.S builds on the stack. The field order must
// match the push order in interrupt.S exactly.
struct InterruptFrame {
    std::uint64_t r15, r14, r13, r12, r11, r10, r9, r8;
    std::uint64_t rbp, rdi, rsi, rdx, rcx, rbx, rax;
    std::uint64_t vector, error_code;
    std::uint64_t rip, cs, rflags, rsp, ss;
};

// 進入使用者模式前保存的核心執行狀態，讓 exit 系統呼叫能跳回這裡返回。
// 欄位順序與偏移量必須與 segment.S 的 x86_64_save_and_enter/restore_and_exit
// 完全一致。
//
// The kernel execution state saved before entering user mode, so the exit
// syscall can longjmp back here and return. The field order and offsets must
// match x86_64_save_and_enter/restore_and_exit in segment.S exactly.
struct UserContext {
    std::uint64_t rbx;     // 0
    std::uint64_t rbp;     // 8
    std::uint64_t r12;     // 16
    std::uint64_t r13;     // 24
    std::uint64_t r14;     // 32
    std::uint64_t r15;     // 40
    std::uint64_t rsp;     // 48
    std::uint64_t rip;     // 56，enter 的返回位址 / the return address into enter
    std::uint64_t rflags;  // 64
};

// CPU 辨識與基本功能啟用。
// CPU identification and basic feature enablement.
void cpu_initialize();
const char* cpu_vendor_string();
// 分頁表需要知道是否可以使用 NX 位元。
// The page tables need to know whether the NX bit is available.
bool cpu_nx_supported();
bool cpu_sse_enabled();

// GDT 與 TSS。
// The GDT and the TSS.
void gdt_initialize();
void gdt_set_kernel_stack(std::uint64_t stack_top);

// IDT 與中斷處理常式表。
// The IDT and the interrupt handler table.
void idt_initialize();
bool idt_register(unsigned vector, InterruptHandler handler, void* context);
void idt_unregister(unsigned vector);

} // namespace shirley::arch::x86_64

extern "C" {
// 由 segment.S 提供的特權指令包裝。
// Privileged instruction wrappers provided by segment.S.
void x86_64_load_gdt(const void* pointer, std::uint16_t code_selector, std::uint16_t data_selector);
void x86_64_load_idt(const void* pointer);
void x86_64_load_tss(std::uint16_t selector);
// 保存核心狀態到 *context，然後以 IRET 進入 ring 3。使用者行程呼叫 exit 時
// 由 x86_64_restore_and_exit 跳回本函式的呼叫端，回傳值即為結束碼。
//
// Save the kernel state into *context, then IRET into ring 3. When the user
// process calls exit, x86_64_restore_and_exit jumps back to this function's
// caller and the return value is the exit status.
long x86_64_save_and_enter(std::uint64_t entry, std::uint64_t stack,
                           std::uint16_t code_selector, std::uint16_t data_selector,
                           shirley::arch::x86_64::UserContext* context);
[[noreturn]] void x86_64_restore_and_exit(shirley::arch::x86_64::UserContext* context, long status);
// 由 interrupt.S 產生的 256 個中斷入口；每個入口佔用相同的位元組數，
// 實際間距由頭尾兩個符號反推，不必在組語與 C++ 兩邊各寫一次。
//
// The 256 interrupt entry points generated by interrupt.S. Each occupies the
// same number of bytes; the stride is derived from these two symbols rather
// than written down in both the assembly and the C++.
extern const char x86_64_isr_stubs[];
extern const char x86_64_isr_stubs_end[];
}
